---
- name: restart ssh
  service: "name={{ security_sshd_name }} state={{ security_ssh_restart_handler_state }}"

- name: restart docker
  service: "name=docker state={{ docker_restart_handler_state }}"

- name: restart nginx
  command: "docker restart nginx-rtmp"

- name: restart stunnel
  service:
    name: stunnel4
    state: "restarted"